### ISSUE TITLE
kafka connector log4j appender file?

### ISSUE THREAD

**Issue by mukthyarazam** [ibm-messaging/kafka-connect-mq-source#10]
Hi Andrew,
I hope you are doing good.  We required kafka-connect-mq-source logs to identify connection issue/ failures, so that we are planning to persist logs in a file hence I modified the [log4j.properties](https://github.com/ibm-messaging/kafka-connect-mq-source/blob/master/src/test/resources/log4j.properties)  as below but its not writing anything  to my_log target file. What is the issue here? What repository changes required to make it run? Is the properties file in right location or folder? Please help with log4j.properties file and steps to make it run in both windows/ unix. thanks 

I dont see PropertyConfigurator.configure("log4j.properties") in java code base..Does it require this configuration?

What are changes required in the repository to make it work 

`# Root logger option
log4j.rootLogger=INFO, file

**Direct log messages to a log file**
log4j.appender.file=org.apache.log4j.RollingFileAppender

#Redirect to Tomcat logs folder
#log4j.appender.file.File=${catalina.home}/logs/logging.log

log4j.appender.file.File=my_log.log
log4j.appender.file.MaxFileSize=10MB
log4j.appender.file.MaxBackupIndex=10
log4j.appender.file.layout=org.apache.log4j.PatternLayout
log4j.appender.file.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n`

One more thing this connector is running fine even with IBM-MQ 7.5.x, Why not you update the help file.

I am not able to figureout  route cause of the issue, also I dont see the META-INF/MANIFEST.MF in this Jar, the file itself which has (at least) this one liner:
**Main-Class: com.mypackage.MyClass**

**Comment by AndrewJSchofield** [comment]
Hi, I'm afraid that I cannot help with the log4j configuration. That's to do with the environment that you're running in, not the connector itself.

I'm happy to see that you have it working with MQ 7.5. I'll update the documentation when I make the next revision.

You're correct that there are problems with the information in the JAR manifest. I need to spend some time cleaning this up, but it should not cause any issues for running the connector.
