### ISSUE TITLE
Avro schema problems with builders

### ISSUE THREAD

**Issue by VenkatJav** [ibm-messaging/kafka-connect-mq-source#100]
I have setup need to read the messages from MQ and post into the pre-defined schema with AVRO format. I try below and it's not working and getting errors. Any idea how can i make it work? incoming messages are not JSON format so i can't use the JSON record builders. 

"mq.record.builder": "com.ibm.eventstreams.connect.mqsource.builders.DefaultRecordBuilder"
"mq.message.body.jms": "true"
"key.converter": "io.confluent.connect.avro.AvroConverter"
"value.converter": "io.confluent.connect.avro.AvroConverter"
"key.converter.schema.registry.url": "https://myschemaregistryURL:port",
"value.converter.schema.registry.url": "https://myschemaregistryURL:port"

**Comment by jhughes24816** [comment]
Hi @VenkatJav, This MQ connector currently supports the default Apache Kafka converters:
- org.apache.kafka.connect.converters.ByteArrayConverter
- org.apache.kafka.connect.storage.StringConverter
- org.apache.kafka.connect.json.JsonConverter
The [Data formats](https://github.com/ibm-messaging/kafka-connect-mq-source#data-formats) section of the README explains how the connector works in this area.

As mentioned in the README you could package a customer but this is quite an involved process. I can highlight this to the development team and this might get addressed in a future release of the connector
