### ISSUE TITLE
Set MQGetMessageOptions on createConsumer

### ISSUE THREAD

**Issue by selamanse** [ibm-messaging/kafka-connect-mq-source#105]
Situation:

I'd like to be able to set MQGetMessageOptions for the created Consumer in the [JMSReader implementation](https://github.com/ibm-messaging/kafka-connect-mq-source/blob/master/src/main/java/com/ibm/eventstreams/connect/mqsource/JMSReader.java#L230).

Question:
Is there a way to set these Options with additional properties or java environment parameters? 

I appreciate any kind of pointer or help.

**Comment by jhughes24816** [comment]
Hi there, This connector uses the JMS API to make the connection to MQ so the MQGetMessageOptions are not available at present. Some aspects of MQGetMessageOptions can be configured on the JMS API which we could look in to exposing. Are there any particular options you are interested in?

**Comment by selamanse** [comment]
Hi @jhughes24816, thank you first for responding so quickly.

I'd like to be able to set at least MQGMO for:
- MatchOptions (MQLONG)
- MQGMO_BROWSE_FIRST
- MQGMO_BROWSE_MSG_UNDER_CURSOR

as documented [here](https://www.ibm.com/docs/en/ztpf/1.1.0.15?topic=structures-get-message-options-mqgmo#mqgmost__matopt2)

**Comment by dalelane** [comment]
hi @selamanse . Would you mind describing the use case for this please? Why is it that you want the Connector to only browse instead of getting messages? If you could describe your goal or objective, we might be able to suggest a way of achieving it.

**Comment by selamanse** [comment]
Hi @dalelane, sure let me try: I am using Kafka Connect to consume messages from an Z/OS based MQ System where the messages are put via cobol routines and have a default setting on the match options which might affect performance. We are already considering 2 options to get more throughput: 

- change index attribute on the queue 
- reduce batches committed by cobol processes 

And as a third option we would like to override the given MQGMOs to have some control over these settings.

I hope this makes sense.

Source I considered as a base for all of this: https://www.ibm.com/support/pages/ibm-mq-performance-issues-getting-messages-queue-large-curdepth

**Comment by selamanse** [comment]
So the 2 options mentioned did not help in my case. I am also measuring "wait" times between polls which could be reduced with MQGMO-WAITINTERVAL=0 settings. 

@dalelane is there any way to set this from outside via environment params?

**Comment by jhughes24816** [comment]
Hi @selamanse, Your suggested use case is broader than what the connector is really intended for. I am tagging @mamwl1 who might be able to help out if you want to discuss options for tackling slow throughput and how to work with these connectors on Z/OS.

**Comment by selamanse** [comment]
@jhughes24816 thanks for the update. Meanwhile we were able to optimize throughput by adding a certain amount of CPU and Memory to the Pods that we are running connect in.

I guess it's not mainframe specific in this case, it's a constellation of resource allocation for the JVM Connect runs in. IMHO the official connect images for connect are not really resource optimized but I cannot tell why atm. I will investigate this further but I guess for the source connector it's not of real relevance.

you can close this if you like.
