### ISSUE TITLE
I am trying to test the connector on Ubuntu Standalone. (host issue)

### ISSUE THREAD

**Issue by chandantroughia** [ibm-messaging/kafka-connect-mq-source#11]
Hi Andrew,

Thanks for the connector code. I hope you are having a great day. My query is kind of trivial but I am somehow not able to make this connector work.
I followed the steps mentioned (from scratch).
My Kafka is working fine. I was able to configure IBM MQ 8.0 as per the steps mentioned (working fine). I followed all the steps but somehow connector is not connecting to the queue.
The errors that I get are as following:
```
JMSCMQ0001: IBM MQ call failed with compcode '2' ('MQCC_FAILED') reason '2538' ('MQRC_HOST_NOT_AVAILABLE').

AMQ9204: Connection to host 'localhost:1414(1414)' rejected. [1=com.ibm.mq.jmqi.JmqiException[CC=2;RC=2538;AMQ9205: The host name supplied is not valid. [3=localhost:1414,4=TCP]],3=localhost:1414(1414),5=RemoteTCPConnection.resolveHostname]

AMQ9205: The host name supplied is not valid

JMSWMQ0018: Failed to connect to queue manager 'MYQM' with connection mode 'Client' and host name 'localhost:1414(1414)'.
Check the queue manager is started and if running in client mode, check there is a listener running.
```
I tried to debug my configuration details i.e. mentioned [here](https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_7.5.0/com.ibm.mq.tro.doc/q045380_.htm)

I think the issue is with this statement: "These instructions set up a queue manager that uses the local operating system to authenticate the user ID and password, and the user ID is called alice and the password is passw0rd."

I created a new user 'alice' with password as mentioned and added alice to mqm group.

If possible please let me know if I may be making a mistake or let me know of any resource that can be helpful.

Warm Regards.

**Comment by AndrewJSchofield** [comment]
I can see from the error message AMQ9204 that the connection name is "localhost:1414(1414)". There are too many 1414s in there. If you're using port 1414 on localhost, I would expect "localhost(1414)". Hope this helps.

**Comment by AndrewJSchofield** [comment]
I think my instructions have a mistake. Sorry. Try:
mq.connection.name.list=localhost(1414)
