### ISSUE TITLE
 Update to strimzi kafka image 2.6.0 to 3.4.0

### ISSUE THREAD

**Issue by david-VigneshN** [ibm-messaging/kafka-connect-mq-source#110]
### Description

We are trying to address the log4j vulnerability in strimzi/kafka:latest-kafka-2.6.0 

### Suggested Solution

Can we update the docker file to use latest kafka version ?

```
FROM strimzi/kafka:latest-kafka-2.6.0 as builder
to
FROM quay.io/strimzi/kafka:latest-kafka-3.4.0 as builder
```

we reviewed changes from 2.6.0 to 3.4.0 , i don't see any breaking changes for kafka connect.
https://kafka.apache.org/downloads

please advice if there are any that we need to consider. 
our initial unit testing shows no issues for MQ source connector

### Additional Context

to address log4j vulnerability

**Comment by Joel-hanson** [comment]
Hello @david-VigneshN,

Thank you for bringing up the issue. We are actively working on updating the packages and images to their latest versions. To achieve this, we plan on building the image from scratch by retrieving the most recent Kafka binaries available. You can find more information on this update in our pull request here: https://github.com/ibm-messaging/kafka-connect-mq-source/pull/109/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R1-R23. We are currently testing the changes against different versions of Kafka and we will merge them as soon as the testing is complete.

Please don't hesitate to let us know if you have any further questions or suggestions.

**Comment by david-VigneshN** [comment]
Thank you @Joel-hanson ! i will watch out the PR.

**Comment by Joel-hanson** [comment]
Marking this issue as closed since the pull request has been successfully merged. Please feel free to reopen this issue if you encounter any further difficulties or have additional concerns.
