### ISSUE TITLE
🐛 [BUG] - Failed to find any class that implements Connector and which name matches com.ibm.eventstreams.connect.mqsource.MQSourceConnector

### ISSUE THREAD

**Issue by kavinrites** [ibm-messaging/kafka-connect-mq-source#115]
### What happened?

When I try to add the connector, I get the below message

curl -X POST -H "Content-Type: application/json" http://localhost:8083/connectors \
  --data "@./mq-source.json"
{"error_code":500,"message":"Failed to find any class that implements Connector and which name matches com.ibm.eventstreams.connect.mqsource.MQSourceConnector, available connectors are: PluginDesc{klass=class org.apache.kafka.connect.mirror.MirrorCheckpointConnector, name='org.apache.kafka.connect.mirror.MirrorCheckpointConnector', version='3.4.0', encodedVersion=3.4.0, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.mirror.MirrorHeartbeatConnector, name='org.apache.kafka.connect.mirror.MirrorHeartbeatConnector', version='3.4.0', encodedVersion=3.4.0, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.mirror.MirrorSourceConnector, name='org.apache.kafka.connect.mirror.MirrorSourceConnector', version='3.4.0', encodedVersion=3.4.0, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockSinkConnector, name='org.apache.kafka.connect.tools.MockSinkConnector', version='3.4.0', encodedVersion=3.4.0, type=sink, typeName='sink', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockSourceConnector, name='org.apache.kafka.connect.tools.MockSourceConnector', version='3.4.0', encodedVersion=3.4.0, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.SchemaSourceConnector, name='org.apache.kafka.connect.tools.SchemaSourceConnector', version='3.4.0', encodedVersion=3.4.0, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.VerifiableSinkConnector, name='org.apache.kafka.connect.tools.VerifiableSinkConnector', version='3.4.0', encodedVersion=3.4.0, type=sink, typeName='sink', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.VerifiableSourceConnector, name='org.apache.kafka.connect.tools.VerifiableSourceConnector', version='3.4.0', encodedVersion=3.4.0, type=source, typeName='source', location='classpath'}"}%

### Environment

```markdown
- OS: MacOS
- Openshift:
- Kubernetes:
```

### Version

1.3.4 (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tekipanda** [comment]
In mq-sink's DockerFile, I see the jar is copied to libs whereas in mq-source it is copied to connectors

sink:
COPY --chown=esuser:esgroup target/kafka-connect-*-jar-with-dependencies.jar /opt/kafka/libs/

source:
COPY --chown=esuser:esgroup target/kafka-connect-*-jar-with-dependencies.jar /opt/connectors

**Comment by jhughes24816** [comment]
Hi @tekipanda, 
Thanks for bringing this to our attention. We should update the sample dockers file provided in the source and sink repo, I will take a look at your PR shortly.

**Comment by david-VigneshN** [comment]
@jhughes24816 quick question, why did we move connector jars to /opt/connectors/ from /opt/kafka/libs/ ? Do we have to set /opt/connectors/ in libpath in this case?
