### ISSUE TITLE
Running Kafka Connector in docker

### ISSUE THREAD

**Issue by ChuOue** [ibm-messaging/kafka-connect-mq-source#12]
Hello, 

Actually I'm running both Kafka and IBM MQ as Docker containers. I followed all the steps but i'm blocked at this one **CLASSPATH=<connector-root-directory>/target/kafka-connect-mq-source-0.5-SNAPSHOT-jar-with-dependencies.jar bin/connect-standalone.sh config/connect-standalone.properties ~/mq-source.properties**. Since I don't know how to specify the classpath for my container. I have tried adding the path using plugin.path at connect-standalone.properties file and running the following command : 

docker run -v /home/pfe/tmp:/kafka/tmp --rm --network network-test ches/kafka connect-standalone.sh config/connect-standalone.properties /kafka/tmp/mq-source.properties 

And this gives the following ERROR : 

[2018-05-22 10:02:49,463] ERROR Failed to create job for /kafka/tmp/mq-source.properties (org.apache.kafka.connect.cli.ConnectStandalone:88)
[2018-05-22 10:02:49,464] ERROR Stopping after connector error (org.apache.kafka.connect.cli.ConnectStandalone:99)
java.util.concurrent.ExecutionException: org.apache.kafka.connect.errors.ConnectException: Failed to find any class that implements Connector and which name 
matches com.ibm.mq.kafkaconnect.MQSourceConnector, available connectors are: org.apache.kafka.connect.source.SourceConnector, 
org.apache.kafka.connect.tools.MockSinkConnector, org.apache.kafka.connect.tools.VerifiableSinkConnector, org.apache.kafka.connect.file.FileStreamSinkConnector, 
org.apache.kafka.connect.file.FileStreamSourceConnector, org.apache.kafka.connect.sink.SinkConnector, org.apache.kafka.connect.tools.MockSourceConnector, 
org.apache.kafka.connect.tools.SchemaSourceConnector, org.apache.kafka.connect.tools.VerifiableSourceConnector, org.apache.kafka.connect.tools.MockConnector
    at org.apache.kafka.connect.util.ConvertingFutureCallback.result(ConvertingFutureCallback.java:80)
    at org.apache.kafka.connect.util.ConvertingFutureCallback.get(ConvertingFutureCallback.java:67)
    at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:96)
Caused by: org.apache.kafka.connect.errors.ConnectException: Failed to find any class that implements Connector and which name matches com.ibm.mq.kafkaconnect.MQSourceConnector, 
available connectors are: org.apache.kafka.connect.source.SourceConnector, org.apache.kafka.connect.tools.MockSinkConnector, 
org.apache.kafka.connect.tools.VerifiableSinkConnector, org.apache.kafka.connect.file.FileStreamSinkConnector, 
org.apache.kafka.connect.file.FileStreamSourceConnector, org.apache.kafka.connect.sink.SinkConnector, org.apache.kafka.connect.tools.MockSourceConnector, 
org.apache.kafka.connect.tools.SchemaSourceConnector, org.apache.kafka.connect.tools.VerifiableSourceConnector, org.apache.kafka.connect.tools.MockConnector
    at org.apache.kafka.connect.runtime.ConnectorFactory.getConnectorClass(ConnectorFactory.java:85)
    at org.apache.kafka.connect.runtime.ConnectorFactory.newConnector(ConnectorFactory.java:38)
    at org.apache.kafka.connect.runtime.AbstractHerder.getConnector(AbstractHerder.java:336)
    at org.apache.kafka.connect.runtime.AbstractHerder.validateConnectorConfig(AbstractHerder.java:235)
    at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.putConnectorConfig(StandaloneHerder.java:158)
    at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:93)

Actually I don't know how to resolve this problem since its my first experience working with both technologies Kafka and IBM MQ And I would really appreciate your help. 
Thank you !

**Comment by AndrewJSchofield** [comment]
I think you already know this, but you're missing the MQ connector JAR from the classpath. You can see that the class "com.ibm.mq.kafkaconnect.MQSourceConnector" isn't found, so you need to build the MQ connector JAR and make sure that Java picks it up. Your Docker container will certainly be getting the Kafka Connect JARs from a directory so you could potentially build an image including the MQ connector JAR using an instruction in your Dockerfile.

**Comment by ChuOue** [comment]
Thank you for your quick answer. I will give you my feedback after trying your proposed solution !

**Comment by AndrewJSchofield** [comment]
Are you still getting the original error message which was "Failed to find any class that implements Connector and which name
matches com.ibm.mq.kafkaconnect.MQSourceConnector"?

**Comment by ChuOue** [comment]
Yes unfortunately I still get the same issue.

**Comment by AndrewJSchofield** [comment]
My suggestion is to double-check that the JAR files for the built-in connectors are in the same directory as the MQ connector you built. My guess is that they are not. You can see in the output that a bunch of connectors are known:
org.apache.kafka.connect.source.SourceConnector,
org.apache.kafka.connect.tools.MockSinkConnector, org.apache.kafka.connect.tools.VerifiableSinkConnector, org.apache.kafka.connect.file.FileStreamSinkConnector,
org.apache.kafka.connect.file.FileStreamSourceConnector, org.apache.kafka.connect.sink.SinkConnector, org.apache.kafka.connect.tools.MockSourceConnector,
org.apache.kafka.connect.tools.SchemaSourceConnector, org.apache.kafka.connect.tools.VerifiableSourceConnector, org.apache.kafka.connect.tools.MockConnector

but the MQ one is not. I expect it's not in the correct directory.
