### ISSUE TITLE
🐛 [BUG] - When reading a message that contains RFH header no exception is being thrown

### ISSUE THREAD

**Issue by jeysanthoshs** [ibm-messaging/kafka-connect-mq-source#120]
### What happened?

When reading a message that contains RFH header no exception is being thrown.

Is there a way to consumer messages that contain RFH message in the header?

### Environment

```markdown
- OS:
- Openshift:
- Kubernetes:
```

### Version

older (<1.3.4)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jhughes24816** [comment]
Hi @jeysanthoshs can you explain why you want an exception to be thrown in these circumstances? is this an enhancement you are after?
