### ISSUE TITLE
🐛 [BUG] - valueSchema is always null

### ISSUE THREAD

**Issue by AishD3** [ibm-messaging/kafka-connect-mq-source#122]
### What happened?

 I am passing below settings in my connector , but its always saying , valueSchema is null , Is my configs needs to be corrected. 

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: mq-source-schema
  labels:
    strimzi.io/cluster: cdt-connect-shared-emp
spec:
  class: com.ibm.eventstreams.connect.mqsource.MQSourceConnector
  config:
    key.converter: io.confluent.connect.avro.AvroConverter
    mq.channel.name: DEV.APP.SVRCONN
    mq.connection.name.list: secureapphelm-ibm-mq-qm(1414)
    mq.password: XXXXXX
    mq.queue: DEV.LOCAL.QUEUE.SOURCE.SCHEMA
    mq.queue.manager: secureapphelm
    mq.record.builder: com.ibm.eventstreams.connect.mqsource.builders.JsonRecordBuilder
    mq.ssl.use.ibm.cipher.mappings: false
    mq.user.name: admin
    tasks.max: 1
    topic: MSk.emp.retinatoolkit.schema.test.v1
    value.converter: io.confluent.connect.avro.AvroConverter
    mq.message.body.jms: false
    value.converter.schema.registry.ssl.key.password: XXXXXXX 
    value.converter.schema.registry.ssl.keystore.location: XXXXXXX/keystore.jks 
    value.converter.schema.registry.ssl.keystore.password: XXXXXX
    value.converter.schema.registry.ssl.truststore.location: /XXXXXXs/truststore.jks
    value.converter.schema.registry.ssl.truststore.password: XXXXXXX 
    value.converter.schema.registry.url: https://XXXXXa-sr.maersk-digital.net
    value.converter.schemas.enable: true 
    key.converter.schema.registry.ssl.key.password: XXXXXX 
    key.converter.schema.registry.ssl.keystore.location: /XXXXXX/keystore.jks
    key.converter.schema.registry.ssl.keystore.password: XXXXXX 
    key.converter.schema.registry.ssl.truststore.location: /XXXXX-certs/truststore.jks
    key.converter.schema.registry.ssl.truststore.password: XXXXXXX
    key.converter.schema.registry.url: https://XXXXXXnet
    key.converter.schemas.enable: false 
    errors.retry.timeout: 3
    errors.retry.delay.max.ms: 10
    errors.tolerance: all
    errors.log.enable: true
    errors.log.include.messages: true
    auto.register.schemas: true
    transforms: ExtractFieldAndOverrideSchema
    transforms.ExtractFieldAndOverrideSchema.type: io.maersk.kafka.connect.ExtractFieldAndOverrideSchema
    transforms.ExtractFieldAndOverrideSchema.field.name: text
    transforms.ExtractFieldAndOverrideSchema.schema.registry.ssl.key.password: XXXXXXXX
    transforms.ExtractFieldAndOverrideSchema.schema.registry.ssl.keystore.location: /XXXXX/sr-certs/keystore.jks
    transforms.ExtractFieldAndOverrideSchema.schema.registry.ssl.keystore.password: XXXXXX
    transforms.ExtractFieldAndOverrideSchema.schema.registry.ssl.protocol: TLS
    transforms.ExtractFieldAndOverrideSchema.schema.registry.ssl.truststore.location: /opt/kafka/external-configuration/sr-certs/truststore.jks
    transforms.ExtractFieldAndOverrideSchema.schema.registry.ssl.truststore.password: XXXXX
    transforms.ExtractFieldAndOverrideSchema.schema.registry.url: https://XXXXX.digital.net
    transforms.ExtractFieldAndOverrideSchema.field.bytes.encoding: UTF_8
    transforms.ExtractFieldAndOverrideSchema.field.type: TEXT
    transforms.ExtractFieldAndOverrideSchema.schema.cache.expiry.secs: 300
    transforms.ExtractFieldAndOverrideSchema.schema.cache.max.size: 1000
    transforms.ExtractFieldAndOverrideSchema.schema.key.enable: true
    transforms.ExtractFieldAndOverrideSchema.schema.value.enable: true

### Steps To Reproduce

Create Connector with above configs and get ValueSchema 

### Environment

```markdown
- OS:
- Openshift:
- Kubernetes:
DEV
```

### Version

1.3.4 (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AishD3** [comment]
ConnectRecord{topic='MSk.emp.retinatoolkit.schema.test.v1', kafkaPartition=null, key=null, keySchema=null, value=[B@29c96fef, **valueSchema=Schema{BYTES},** timestamp=null, headers=ConnectHeaders(headers=)}. (org.apache.kafka.connect.runtime.errors.LogReporter) [task-thread-mq-source-schema-0]

Now ValueSchema is in Bytes , how to convert to String or Json or Avro

**Comment by jhughes24816** [comment]
@AishD3 can you provide more detail as to what you are trying to do please?
