### ISSUE TITLE
Connectors V2 is it a new release 

### ISSUE THREAD

**Issue by AishD3** [ibm-messaging/kafka-connect-mq-source#123]
### Description

https://community.ibm.com/community/user/integration/blogs/matu-agarwal1/2023/09/20/ibm-mq-connector-v2-released?CommunityKey=739928b5-06d5-452d-a013-f688dea8f64a

Is this a new release and Is it not open source and Does it handle AvroConvertor and Does it have new types of RecordBuilders supportive to SMT

### Suggested Solution

https://community.ibm.com/community/user/integration/blogs/matu-agarwal1/2023/09/20/ibm-mq-connector-v2-released?CommunityKey=739928b5-06d5-452d-a013-f688dea8f64a

Is this a new release and Is it not open source and Does it handle AvroConvertor and Does it have new types of RecordBuilders supportive to SMT

### Alternatives

https://community.ibm.com/community/user/integration/blogs/matu-agarwal1/2023/09/20/ibm-mq-connector-v2-released?CommunityKey=739928b5-06d5-452d-a013-f688dea8f64a

Is this a new release and Is it not open source and Does it handle AvroConvertor and Does it have new types of RecordBuilders supportive to SMT

**Comment by matuagarwal** [comment]
Hi @AishD3 
Its a new version of the connector, available under IBM license
yes, the v2 connector works with AvroConverter and SMTs
let me know if more queries

**Comment by slachiewicz** [comment]
The article points to this repo, but it's not clear if the source code of this connector will be available here or the connector is no longer open source?

**Comment by david-VigneshN** [comment]
I don't think they are the same.. v2 connector comes from IBM license is not open source . It has support for EOS which i believe the connector from this repo don't have the feature enabled or updated. 

@dalelane @Joel-hanson pls confirm.

**Comment by matuagarwal** [comment]
This repository hosts open-source MQ-Kafka connectors for version 1, which remain accessible, with ongoing contributions from IBM. 

Additionally, version 2 of the connector as been incorporated into IBM MQ Advanced, Cloud Pak for Integration, and Event Automation product. Hope this helps

**Comment by AishD3** [comment]
Do we have any documentation for V2 ,as V1 is not testing with Confluent Convertors like AvroConvertor , Is V2 tested with AvroConvertor.

**Comment by matuagarwal** [comment]
Connector catalog has documentation details for the v2 connector
https://ibm.github.io/event-automation/connectors/kc-source-ibm-mq2/installation

I will get back on your ValueSchema query.
