### ISSUE TITLE
Reg New Lisenced Version 

### ISSUE THREAD

**Issue by AishD3** [ibm-messaging/kafka-connect-mq-source#126]
### What happened?

It's not a bug but we can see a licensed version of library is also released . Based on that I have few more questions , 
1. Is it compulsory for everyone to upgrade to licensed version or can we continue with version 1 which is open source.
2. What happens if in case if we find some bug in open source will it be supported still .

### Environment

```markdown
- OS:
- Openshift:
- Kubernetes:
```

### Version

1.3.4 (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matuagarwal** [comment]
1- Version 1 repo would continue to exist as open-source
2- Bug raised can be addressed via community contribution...
