### ISSUE TITLE
🐛 [BUG] - Start MQ Source Connector on Kubernetes 

### ISSUE THREAD

**Issue by tony-joseph-nm** [ibm-messaging/kafka-connect-mq-source#128]
### What happened?

It requires to run a curl command once the connector instance/container is running. However this is not practical to trigger the plugin externally on an adhoc basis especially on kubernetes workload. 

### Steps To Reproduce

can you please add sidecar/operator/postStart handler? to start the plugin

### Environment

```markdown
- OS:
- Openshift:
- Kubernetes:
```

### Version

1.3.4 (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jhughes24816** [comment]
Hi tony can you provide more details on what you were doing, environment, when got stuck and what rest calls you used to get the connector started?

**Comment by dalelane** [comment]
Hi Tony

`kafka-connect-mq-source` is a plugin for a framework called "Kafka Connect", which is a component of Apache Kafka. The REST API you're talking about your experience using `curl` to call is a part of the Kafka Connect framework, and not something unique or specific for this particular plugin. You can find out more about it at https://kafka.apache.org/documentation/#connect_rest if you'd like to learn more. 

If you want to run Kafka Connect without using a REST API, you have many options. Your best place to learn about these is the Kafka documentation at https://kafka.apache.org/documentation/#connect_running but I'll give you a brief summary here as well: 
- "stand-alone mode" - run like this, the config is provided through a properties file - no REST API or curl needed
- "distributed mode" - run like this, the config is provided through a REST API which it sounds like has been your experience so far.

They are the options from Apache / Kafka Connect itself, but if you get something else to run/orchestrate Kafka Connect for you, then you have other options as well. For example, at IBM, we have a product called "[IBM Event Streams](https://ibm.github.io/event-automation/es/)" which is Apache Kafka plus extra pieces to make it easier for you to run and manage Kafka. One of those extra pieces is support for declaring what you want to run in Kafka Connect as Kubernetes custom-resources. Our Kubernetes operator then makes the relevant REST API calls to Kafka Connect on your behalf to keep your connectors running as described in the custom-resources. 

There are other non-commercial tools that do this sort of thing as well, such as the open source operator "[Strimzi](https://strimzi.io)". 

None of these change the fact that Kafka Connect has a REST API to control the lifecycle of connectors, but they do drive the REST API for you, which can be very convenient. I hope this helps you with your exploration of Kafka Connect. 

If you'd like to learn more, I'd recommend:

- [IBM Event Streams documentation about starting a Kafka Connect connector using our operator](https://ibm.github.io/event-automation/es/connecting/setting-up-connectors/#start-a-connector)
- [Strimzi documentation about starting a Kafka Connect connector using the open source operator](https://strimzi.io/docs/operators/latest/full/deploying.html#proc-deploying-kafkaconnector-str)
- [Kafka Connect (O'Reilly) - chapter on adminstering Kafka Connect using the REST API](https://learning.oreilly.com/library/view/kafka-connect/9781098126520/ch07.html#administering_kafka_connect_using_the_r)
