### ISSUE TITLE
While using 6 tasks and connect worker gets stopped and started due to a wrong format message , Duplicate messages are received in Kafka

### ISSUE THREAD

**Issue by AishD3** [ibm-messaging/kafka-connect-mq-source#129]
### What happened?

While using 6 tasks and connect worker gets stopped and started due to a wrong format message , Duplicate messages are received in Kafka

### Steps To Reproduce

While using 6 tasks and connect worker gets stopped and started due to a wrong format message , Duplicate messages are received in Kafka

### Environment

```markdown
While using 6 tasks and connect worker gets stopped and started due to a wrong format message , Duplicate messages are received in Kafka
```

### Anything else?

While using 6 tasks and connect worker gets stopped and started due to a wrong format message , Duplicate messages are received in Kafka

### Version

1.3.4 (Default)

### Relevant log output

```shell
While using 6 tasks and connect worker gets stopped and started due to a wrong format message , Duplicate messages are received in Kafkav
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matuagarwal** [comment]
Hi @AishD3 

Exactly once delivery (which avoid duplication) is available only with MQ v2 connector
https://ibm.github.io/event-automation/connectors/kc-source-ibm-mq2/installation

**Comment by dalelane** [comment]
Closing (as the connector here only offers at-least-once delivery, so duplicate messages are possible when the connector is restarted)

For use cases where exactly-once assurances are required, we recommend using the connector that Matu links to above.
