### ISSUE TITLE
Huge connector output when queue manager connection broken

### ISSUE THREAD

**Issue by mark-whitlock** [ibm-messaging/kafka-connect-mq-source#13]
I was using the connector to move messages from an MQ queue to a Kafka topic, when I ended my queue manager. I wanted to test what would happen and check that the connector would successfully reconnect when I restarted my queue manager. I was redirecting the output from the connector to a file on disk. When the queue manager was stopped, the connector continuously output a large number of exceptions, so that the connector output file on disk grew by about half a gig every minute. Luckily I noticed the problem before it filled my disk, but had I not noticed it would not take long before it filled my disk. Does the connector need to retry connecting to the queue manager in a tight loop? Or would it be sufficient to retry every 10 seconds or so? Thanks

**Comment by AndrewJSchofield** [comment]
Fixed in v1.0.
