### ISSUE TITLE
🐛 [Compatibility with AWS (MSK)] - <Is this connector able to be used in AWS for MSK>

### ISSUE THREAD

**Issue by brian-heady** [ibm-messaging/kafka-connect-mq-source#133]
### What happened?

Is this connector able to be used in AWS for MSK?

### Environment

```markdown
AWS
MSK
```

### Version

1.3.4 (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Joel-hanson** [comment]
@brian-heady yes you can use this connector in MSK
