### ISSUE TITLE
💡 [Feature] - Empty JMS messages support in DefaultRecordBuilder

### ISSUE THREAD

**Issue by SuperCD** [ibm-messaging/kafka-connect-mq-source#134]
### Description

Right now if a JMS message is sent and it has an empty MQRFH2 format field (MQFMT_NONE) and an empty body, it becomes an instance of Message, instead of Binary Message and causes an exception at https://github.com/ibm-messaging/kafka-connect-mq-source/blob/6d2b93902407cd6f5c19ae3bd2b9427c4ee1a234/src/main/java/com/ibm/eventstreams/connect/mqsource/builders/DefaultRecordBuilder.java#L75

### Suggested Solution

Just set the value as an empty byte array if the message has an empty payload

**Comment by dalelane** [comment]
@SuperCD Thanks for the suggestion - we've added it to https://github.com/ibm-messaging/kafka-connect-mq-source/releases/tag/v1.3.5 and we'll make an equivalent update to the v2.x connector in due course.
