### ISSUE TITLE
Avro Converter Support 

### ISSUE THREAD

**Issue by ipekdedekoy** [ibm-messaging/kafka-connect-mq-source#140]
Hello Team , 

We are using ibm source/sink connector classes ( com.ibm.eventstreams.connect.mqsource.MQSourceConnector / com.ibm.eventstreams.connect.mqsink.MQSinkConnector )  in order to send data to Kafka/Axual Cloud and receive data from Kafka to IBM MQ. 

As the 3rd party consumers are using AVRO format in their schema and topics we would like to use AVRO connector in our source connectors while sending the data. 
Could you please guide us how to use avro convertor and schema registry with mTLS configuration in our JSON source connecter class ? We would like to use value.converter: io.confluent.connect.avro.AvroConverter and learn that can the mq source connect support AVRO/ Confluent Schema Registry and correctly infer the schema of json object published to MQ. 

Thanks 
IPEK

**Comment by dalelane** [comment]
There isn't a generic way for the MQSourceConnector to infer the structure from the messages that it gets from the MQ queue, so the current answer for this will involve a little custom code. 

The `mq.record.builder` config option for the Connector is used to specify the class that you want to infer the schema/structure from the MQ messages. You can use this to point at a class that you create yourself:

```java
public class YourCustomRecordBuilder extends BaseRecordBuilder {

    @Override
    public SchemaAndValue getValue(final JMSContext context, final String topic, final boolean messageBodyJms, final Message message) throws JMSException {
        // RETURN A KAFKA CONNECT STRUCTURED RECORD WITH A SCHEMA
    }
}
```

This method will be called with the message retrieved from MQ, and can return any arbitrary Kafka Connect [schema](https://kafka.apache.org/37/javadoc/org/apache/kafka/connect/data/Schema.html) and [value](https://kafka.apache.org/37/javadoc/org/apache/kafka/connect/data/Struct.html). Returning a Kafka Connect schema and value means your records will be supported by any Kafka Connect converter - including an Avro or Confluent converter.

**Comment by dalelane** [comment]
In case it helps, I've written up a more detailed answer and example at https://dalelane.co.uk/blog/?p=5337
