### ISSUE TITLE
Connector for Native MQ

### ISSUE THREAD

**Issue by michaeljquinn** [ibm-messaging/kafka-connect-mq-source#2]
Fantastic first steps

Please forgive my ignorance, but this connector seems to be for JMS/MQ

Will this work for a native MQ connections (I want to consume binary and/or XML messages) from clients
putting to a MQ Q (not JMS)

thanks

**Comment by AndrewJSchofield** [comment]
Yes, it will. Just configure the connector for binary messages and the messages will just flow through untouched. The connector uses the JMS API internally, but by default it turns off the JMS-specific processing and just treats everything as bytes.

**Comment by michaeljquinn** [comment]
Andrew - thats perfect - I tried it out today and it worked perfectly - 
Now I can process MQ messages without Bluemix bridge - you rock !!!
