### ISSUE TITLE
Connector fails with more than 1 partition where queue sets MaxUncommittedMsgs: 10,000

### ISSUE THREAD

**Issue by michyliao** [ibm-messaging/kafka-connect-mq-source#20]
The connector error'd out when we increased our partition for our topic to 2 : 

`JMSCMQ0001: IBM MQ call failed with compcode '2' ('MQCC_FAILED') reason '2024' ('MQRC_SYNCPOINT_LIMIT_REACHED')`

The threads are not committing the read and have reach the Sync Point Limit. Is it possible to return the MQCMIT call to be less than the default queue value? (10000 calls)

**Comment by AndrewJSchofield** [comment]
Hi, I guess that you're using version 1.0.1 or older of the connector. I suggest you try the latest (1.0.2) version. The design for handling syncpoint is quite different and the problem should no longer be present. That is my recommendation.

If you want to stick with the current version, you can tune the `offset.flush.interval` to a smaller value such as 2000. The documentation here (https://github.com/ibm-messaging/kafka-connect-mq-source/blob/64e5253c5a89681fe1d3bd45006fe2dc4fd047dc/README.md) describes this. Essentially, the connector is building very large units of work and this config value controls how frequently commit is being processed.

Hope this helps.

**Comment by AndrewJSchofield** [comment]
Any progress here?

**Comment by michyliao** [comment]
We had to adjust the offset.flush.interval setting! Thanks!
