### ISSUE TITLE
"trace":"java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by michyliao** [ibm-messaging/kafka-connect-mq-source#21]
Hi, 

I just recently built the connector, but when I connect to our MQ source, I am getting the following error:

`"trace":"java.lang.NoSuchMethodError: javax.jms.Connection.createSession(I)Ljavax/jms/Session;\n\tat com.ibm.msg.client.jms.admin.JmsConnectionFactoryImpl.createContext(JmsConnectionFactoryImpl.java:531)\n\tat com.ibm.eventstreams.connect.mqsource.JMSReader.connect(JMSReader.java:191)\n\tat com.ibm.eventstreams.connect.mqsource.MQSourceTask.start(MQSourceTask.java:84)\n\tat org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:198)\n\tat org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)\n\tat org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\n"`

I am unsure of which package I should be uploading - since a lot of the posts I've found online is saying to update to jms 1.2 , but in the current pom.xml  - it is already at 2.0

Thanks

**Comment by AndrewJSchofield** [comment]
It looks to me like you've not got the JMS JAR on the classpath. The instructions mention using the JAR file that have -with-dependencies in its name. This is a fat JAR that contains all of the prereqs. If you're using that, I don't which understand the problem. If you're using the JAR without the dependencies, you'll need to put the MQ and JMS JARs on the classpath for the Kafka Connect workers.

Hope this helps.

**Comment by michyliao** [comment]
Hey andrew,

I was using the fat JAR with dependencies - and i still got a no such method error, reason why im asking if there are any additional classes that I need to include. This error only shows up after we connect to the MQ source.

Thanks

**Comment by AndrewJSchofield** [comment]
I'm not aware of any additional JARs that you would need. The JAR -with-dependencies should contain them all and when I test it I just put that single JAR into Kafka Connect's classpath and it works.

**Comment by AndrewJSchofield** [comment]
Closing because dormant.
