### ISSUE TITLE
MQ Message persistance behavior

### ISSUE THREAD

**Issue by SAshish19** [ibm-messaging/kafka-connect-mq-source#27]
Hello,

I had posted a query for Sink adapter regrading the message persistence and I discovered that the sink adapter may send duplicate messages to avoid loosing the messages. Is the same behavior valid for Source Adapter as well ?

Read the message from MQ Queue---->Deliver the message to Kafka Topic------>Once the message has been delivered to Kafka Topic, issue a COMMIT for MQ GET.

In this case, if the adapter get killed just before issuing the COMMIT(and after the message is delivered to Kafka Topic), the message would be rolled back to the Queue and Adapter would re-process the same message upon restarting.

Please let me know if my understanding is correct.

**Comment by AndrewJSchofield** [comment]
You are correct. There is a small possibility of message duplication in situations like this.
