### ISSUE TITLE
"Failed to flush" "timed out while waiting for producer to flush"  & "Failed to commit offsets"  error with SSL setup

### ISSUE THREAD

**Issue by SAshish19** [ibm-messaging/kafka-connect-mq-source#34]
Hello,

I am trying to setup SSL between : 

- This connector and MQ (One way SSL.)
- This connector and Kafka Server (To begin with One Way SSL)

I have made the necessary changes in the connect-standalone.properties(for worker) and  server.properties(for Kafka Server).  The connector is successfully able to make SSL connections with IBM MQ. The corresponding channel is getting started in SSL mode once we configure the SSL configurations.  The adapter is also able to connect with Kafka (I don't see any errors while starting the connector)
[Connector_error.log](https://github.com/ibm-messaging/kafka-connect-mq-source/files/3397008/Connector_error.log)

To verify the Kafka Server SSL setup , I tested with kafka-console-consumer.sh and kafka-console-producer.sh in SSL mode and it worked fine. I am able to make SSL connections and push/consume messages using  console-producer.sh & kafka-console-consumer.sh. 

The issue however comes when I use the connector in SSL mode. When a message is placed to the input queue, its not getting delivered to the Kafka Server Topic. The message remains in Uncommitted state on the queue and I keep getting below entry in the connector log. No such error comes if I start the adapter in SSL disabled mode. The message is successfully delivered to the Topic in SSL disabled mode. Log entry : 

[2019-07-16 12:15:22,315] INFO WorkerSourceTask{id=mq-source-0} flushing 1 outstanding messages for offset commit (org.apache.kafka.connect.runtime.WorkerSourceTask:414)
[2019-07-16 12:15:27,316] ERROR WorkerSourceTask{id=mq-source-0} Failed to flush, timed out while waiting for producer to flush outstanding 1 messages (org.apache.kafka.connect.runtime.WorkerSourceTask:419)
[2019-07-16 12:15:27,316] ERROR WorkerSourceTask{id=mq-source-0} Failed to commit offsets (org.apache.kafka.connect.runtime.SourceTaskOffsetCommitter:111)

Below are the SSL configuration details from the connect_standalone.properties and server.properties files

**connect-standalone.properties**
security.protocol=SSL
ssl.truststore.location=new_connector_ts.jks
ssl.keystore.location=new_connector_ks.jks
ssl.truststore.password=XXXXXXX
ssl.keystore.password=XXXXXXX
ssl.endpoint.identification.algorithm=

**server.properties**
listeners=PLAINTEXT://172.31.46.133:9092,SSL://172.31.46.133:9093
advertised.listeners=PLAINTEXT://172.31.46.133:9092,SSL://172.31.46.133:9093
listener.security.protocol.map=SSL:SSL,PLAINTEXT:PLAINTEXT
inter.broker.listener.name=PLAINTEXT
ssl.truststore.location=new_kafka_ts.jks
ssl.truststore.password=XXXXXX
ssl.keystore.location=new_kafka_ks.jks
ssl.keystore.password=XXXXX
ssl.key.password=XXXXX
ssl.client.auth=none
ssl.enabled.protocols=TLSv1.2,TLSv1.1,TLSv1
ssl.keystore.type=JKS
ssl.truststore.type=JKS
ssl.endpoint.identification.algorithm=

Could you please assist. Attaching the connector log. Kindly let me know if any further info is required on this.

Thanks & Regards

**Comment by AndrewJSchofield** [comment]
I think your configuration for connecting to Kafka is incorrect. You need to duplicate all of the SASL and SSL configuration in the connect-standalone.properties with producer on the front too. So something like:

```
security.protocol=SSL
ssl.truststore.location=new_connector_ts.jks
ssl.keystore.location=new_connector_ks.jks
ssl.truststore.password=XXXXXXX
ssl.keystore.password=XXXXXXX
ssl.endpoint.identification.algorithm=
producer.security.protocol=SSL
producer.ssl.truststore.location=new_connector_ts.jks
producer.ssl.keystore.location=new_connector_ks.jks
producer.ssl.truststore.password=XXXXXXX
producer.ssl.keystore.password=XXXXXXX
producer.ssl.endpoint.identification.algorithm=
```

**Comment by SAshish19** [comment]
Thanks Andrew.The solution worked for me perfectly. 

Regards

**Comment by SAshish19** [comment]
Resolving the open issue
