### ISSUE TITLE
Make parameter USER_AUTHENTICATION_MQCSP configurable

### ISSUE THREAD

**Issue by mtghunt** [ibm-messaging/kafka-connect-mq-source#41]

**Comment by mtghunt** [comment]
i have created a pull request. Please review

**Comment by AndrewJSchofield** [comment]
Please can you give me some idea why this is a good idea? It doesn't seem like a desirable feature to me.

**Comment by flojon** [comment]
Hi,

We would also like to have this config option.
We need USER_AUTHENTICATION_MQCSP to be false to be able to connect to our company MQ server. If it's true the MQ server tries to authenticate as the executing user instead of using the username and password supplied in the properties.

**Comment by AndrewJSchofield** [comment]
Right but isn't setting this to true essentially telling the MQ client to use a modern way of passing credentials, not the original way? Are you trying to talk to an old version of MQ?

**Comment by mtghunt** [comment]
Me met this problem with out ibm mq server. Also confluent ibm mq kafka connector supports this param

**Comment by flojon** [comment]
Not sure how old version of MQ it is. Could look it up. But so far setting USER_AUTHENTICATION_MQCSP to false is the only way I've been able to connect.

**Comment by mtghunt** [comment]
The same we have.

**Comment by AndrewJSchofield** [comment]
OK, but the default must be TRUE. I'll take another look at the PR soon.

**Comment by AndrewJSchofield** [comment]
I've added the capability. Try setting the config `mq.user.authentication.mqcsp=false` to turn off use of MQCSP.
