### ISSUE TITLE
Add additional configuration for SSL keystores

### ISSUE THREAD

**Issue by MatthiasBechtold** [ibm-messaging/kafka-connect-mq-source#44]
When connecting to a secure MQ Channel, a personal SSL certificate (private key) may be required to establish TLS.
This should be supported in some way.

I suggest providing two JKS files (as paths on the local filesystem), each with their respective password as well, to serve as "TrustStore" and "KeyStore". Those will be optional in the configuration, so the change will be backward compatible.

I am providing a pull request with my implementation.

**Comment by MatthiasBechtold** [comment]
Please have a look at #45

**Comment by MatthiasBechtold** [comment]
I did not take fully into account what is written in the README.md when describing my issue first. Sorry for that, please let me elaborate:

Yes, in fact TLS mutual auth. will *work* if one adds a personal certificate to a workers JVM.
*But* - I think it is not much of an unusual case running multiple different connectors on a worker.
This bears several problems:

1. Sharing a single private key is not always desirable
2. Having multiple different private keys in the same JVM keystore cannot work afaik (how is the correct key selected for a specific connection?)
3. A JKS type keystore password *must* exactly match the private key encryption password, otherwise decryption fails

**Comment by AndrewJSchofield** [comment]
Also, the PR must include a statement of acceptance of the Contributor License Agreement (see CLA.md).

**Comment by AndrewJSchofield** [comment]
Thanks for the PR. Merged.
