### ISSUE TITLE
Use of Glassfish application server

### ISSUE THREAD

**Issue by SAshish19** [ibm-messaging/kafka-connect-mq-source#48]
Hello,

This is more of a query rather than an issue. I am working with Kafka connect worker in distributed mode. While going through the logs post I started the worker, I see some logs for Glassfish. My idea of this was that its a standalone java process which needs a Java runtime to execute rather than a fully fledged application server. The worker uses Java runtime to start and creates a REST service that by default listens to requests on port 8083. Not very sure as to how is Glass fish coming into picture. May be my understanding is completely wrong but it would help to have some insights on this 

Thanks & Regards

**Comment by AndrewJSchofield** [comment]
I'm afraid I don't know. Probably worth asking on the Kafka users mailing list.
