### ISSUE TITLE
No support for Custom Partition key?

### ISSUE THREAD

**Issue by krishmah** [ibm-messaging/kafka-connect-mq-source#49]
Wanted to check if there is no provision to have custom partition key? We want to read messages from MQ and have it partitioned based on key field in the MQ message before pushing them to Kafka

**Comment by AndrewJSchofield** [comment]
There is limited support for setting a partitioning key. Which specific information do you want to use for partitioning?

**Comment by krishmah** [comment]
Want to use one of the message attributes from MQ Message as Partition Key. How do I set them?

**Comment by AndrewJSchofield** [comment]
There's no support for specific named MQ message properties as the partitioning key. If you can tell me specifically what you're trying to do, I will be able to understand how much work it would take to add it. I'm happy to add new features based on requirements.

**Comment by AndrewJSchofield** [comment]
Closing dormant issue.
