### ISSUE TITLE
Does it support Confluent Schema Registry? 

### ISSUE THREAD

**Issue by alpeza** [ibm-messaging/kafka-connect-mq-source#50]
Hi
Does exists any option to cast the records to AVRO ,that stores the AVRO schema in the Confluent Schema Registry?

Thanks

**Comment by AndrewJSchofield** [comment]
Hi. The connector works perfectly with Avro.

**Comment by alpeza** [comment]
Thanks for the reply.

My question is if the connector is compatible with the settings defined in
https://docs.confluent.io/4.1.2/schema-registry/docs/connect.html


for example use the AvroConverter:

```
value.converter=io.confluent.connect.avro.AvroConverter
```

Thanks

**Comment by AndrewJSchofield** [comment]
Yes.
