### ISSUE TITLE
JMS 2.0 API Issue

### ISSUE THREAD

**Issue by AdiBhave** [ibm-messaging/kafka-connect-mq-source#51]
Hi, 

I am using this repository to build a JAR to connect to an BMC WMQ. The Queue runs on the 8.0.0.13 version. But still I get the following error while submitting a connector

“ JMSCC5007: Use of ‘createContext()’ is not supported with this instance of this connection. Only connections with a correct type of connection can support using the JMS 2.0 API”

**Comment by AndrewJSchofield** [comment]
Take a look at this: https://www.ibm.com/support/knowledgecenter/SSFKSJ_9.0.0/com.ibm.mq.tro.doc/q120080_.htm

**Comment by AndrewJSchofield** [comment]
Closing dormant issue. Please reopen if required.
