### ISSUE TITLE
Error while connecting Mq Version 7.5.0.8

### ISSUE THREAD

**Issue by mukthyarazam** [ibm-messaging/kafka-connect-mq-source#6]
First I would like to thank for sharing this mq connector repo in github.

We are using MQ version 7.5.0.8 and facing below errors while running it can you please share/ suggest the changes required in the code base to make it work. Thank you

{"name":"kafka-mq-connector", "connector":{"state":"RUNNING", "worker_id":"191.111.222.75:8083"}, "tasks":[{"state":"FAILED","trace":"org.apache.kafka.connect.errors.ConnectException:com.ibm.msg.client.jms.DetailedJMSException: JMSCC0091: The provider factory for connection type 'com.ibm.msg.client.wmq' could not be loaded.\n\tat com.mqkafka.kafkaconnector.MQReader.configure(MQReader.java:122).\n\tat com.mqkafka.kafkaconnector.MQSourceTask.start(MQSourceTask.java:36).\n\tat org.apache.kafka.connect.runtime.WorkerSourceTask.execut(WorkerSourceTask.java:157).\n\tat org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170).\n\tat org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214).\n\tat

**Comment by AndrewJSchofield** [comment]
Please could you confirm which version of the connector you're using. I changed the way it gets the MQ JAR file in 0.3 so I wonder whether you're using the previous 0.2 or current 0.3 version.

**Comment by AndrewJSchofield** [comment]
We've taken a look at the stack trace and believe that the problem is related to the environment in which the connector is running (such as the classpath) and not to do with the version of MQ that is being used.

**Comment by mukthyarazam** [comment]
Thanks for your response.. its looks like issue with [uber jar build](https://stackoverflow.com/questions/48309532/error-while-kafka-connect-with-mq-source)

**Comment by AndrewJSchofield** [comment]
OK, glad to hear that you've got to the bottom of it.
