### ISSUE TITLE
Hashed/encoded passwords & Connection Handling  

### ISSUE THREAD

**Issue by SAshish19** [ibm-messaging/kafka-connect-mq-source#60]
Hello,

I am running the connector on a distributed worker. The worker connects to the kafka infrastructure over TLS and SCRAM Authentication. Since , these security mechanisms are in place I have updated the below password specific details in the connect-distributed.properties file.

1-password for connecting to Kafka Broker in sasl.jaas.config property
2-password for the keystore and truststore being used 

Similarly for accessing the connector over RSTAPI interface I have enabled userid/password based authentication which also has the password updated in the text file
Is there a way these passwords can be encoded and the jar accepts the encoded format ?

2-nd query is how the connection is handled with IBM MQ. Does the connection remain active 24x7 ? Or it remains idle if there is period of inactivity or consumes messages as soon as they arrive ?

Thanks  & Regards

**Comment by AndrewJSchofield** [comment]
Hi,
The best way of handling secrets is described here: https://github.com/ibm-messaging/kafka-connect-mq-source#externalizing-secrets

The connection to MQ remains open. It is intended for sending messages continuously.
Hope this helps.

**Comment by SAshish19** [comment]
Thanks Andrew. Please correct me if I am wrong but this section refers to the secret related to the end systems being configured via the connector e.g. if we are using MQ connector we can give the password for MQ using "mq.password" while starting connector. There are other passwords as well like keystore password , truststore password for connector or Jaas config password for SCRAM authentication which are stored in the distributed worker file. Just wanted to check if any such capability is there which handles encoded passwords from the worker properties file.

**Comment by AndrewJSchofield** [comment]
I'm not sure but I think you can do the same thing in the worker properties file.

**Comment by SAshish19** [comment]
I checked and found that, the worker properties file ssl keystore and truststore attributes apply to Connector--->Kafka SSL config. For connector ---->MQ Config we would have to set it specifically via Djavax attributes before starting the connector process

export EXTRA_ARGS="-Dcom.ibm.mq.cfg.useIBMCipherMappings=false -Djavax.net.ssl.keyStore='key.jks' -Djavax.net.ssl.keyStorePassword='<xxx>' -Djavax.net.debug=all -Djavax.net.ssl.trustStore=truststore.jks -Djavax.net.ssl.trustStorePassword=<xxxx>"

In that case, I believe

**Comment by AndrewJSchofield** [comment]
I think you can do that. You might need to write a config provider that can handle the encrypt/decrypt.
