### ISSUE TITLE
Part of the message consumed from MQ is string

### ISSUE THREAD

**Issue by jay999123** [ibm-messaging/kafka-connect-mq-source#63]
Hi,
I'm consuming from MQ using following settings :

{
    "name": "MQ_Source_Connector",
    "config":{
        "connector.class": "com.ibm.eventstreams.connect.mqsource.MQSourceConnector",
        "tasks.max": "1",
        "topic": "mq_kafka_topic",
        "value.converter": "org.apache.kafka.connect.converters.ByteArrayConverter",	
        "mq.queue.manager": "MQ2",
        "mq.connection.name.list": "1.1.1.1(1111)",
        "mq.channel.name": "KH.TEST",
        "mq.queue": "KH.LOCAL",
        "mq.record.builder": "com.ibm.eventstreams.connect.mqsource.builders.DefaultRecordBuilder",
		"mq.user.name": "ABCD"
		
    }
}

What I've observed is, part of the message when I see in the kafka topic, is in the `String`format, and the other part in `bytes` format.
E.g., `5088888�������������@�����@����������@�����`

And when I changed the converter to String as follows - 

        "value.converter": "org.apache.kafka.connect.storage.StringConverter",
        "mq.message.body.jms": "true",
        "mq.record.builder": "com.ibm.eventstreams.connect.mqsource.builders.DefaultRecordBuilder",

I see in the topic as the vice-versa -
`�������EC990TESTING3300`

Any idea why is this behaviour ?

**Comment by AndrewJSchofield** [comment]
That's because when you ask for the plain bytes, it gives you the plain bytes, no conversion. In the second case, you asked for a conversion. As it says in the documentation, you need to understand the format of the MQ messages and set the conversion options accordingly.

**Comment by AndrewJSchofield** [comment]
Closing dormant issue.
