### ISSUE TITLE
Setting up Mutual TLS with MQ failed

### ISSUE THREAD

**Issue by SAshish19** [ibm-messaging/kafka-connect-mq-source#65]
Hello,

Working with distributed worker where the distributed worker properties file has the keystore and truststore with certs needed for kafka broker connectivity. While setting up mutual TLS for MQ, I am getting 

AT QUEUE MANAGER AMQ9637E: Channel is lacking a certificate.
AT DISTRIBUTED WORKER AMQ9503: Channel negotiation failed

I started the distributed worker process without any Djavax.net.ssl.keyStore or Djavax.net.ssl.trustStore attributes being specified in  EXTRA_ARGS  env variable and only added the mq.ssl.keystore.location/mq.ssl.trustorestore.location (along with password attributes) to the connector [Start the distributed worker process---->issue the curl input to create a connector and in this input pass keystore and truststore with certs specific to MQ]

This attempt fails with above error. 

However if I do not specify any SSL related information in the connector via the variables mq.ssl.keystore.location/mq.ssl.trustorestore.location and only specify the keystore/truststore details for worker process via below process, the mutual SSL works

export EXTRA_ARGS="-Dcom.ibm.mq.cfg.useIBMCipherMappings=false -Djavax.net.ssl.keyStore='key.jks' -Djavax.net.ssl.keyStorePassword='<xxx>' -Djavax.net.debug=all -Djavax.net.ssl.trustStore=truststore.jks -Djavax.net.ssl.trustStorePassword=<xxxx>"

Then start the distributed worker--->create a new connector and do not specify the keystore/truststore details via mq.ssl.keystore.location/mq.ssl.trustorestore.location attributes------>The connector works and MQ channel is started in Mutual SSL mode

Do we need to still export the keystore and truststore with EXTRA_ARGS if we are already passing the truststore and keystore on the connector. The documentation says - 

_"You will need to put the public part of the client's certificate in the queue manager's key repository. You will also need to configure the worker's JVM with the location and password for the keystore containing the client's certificate. Alternatively, you can configure a separate keystore and truststore for the connector."_

I guess if I am passing the keystore and truststore in the connector ideally there should not be any requirement to pass the same   via EXTRA_ARGS

**Comment by AndrewJSchofield** [comment]
You should be able to do it all with the configuration parameters for keystore and truststore location these days.

**Comment by SAshish19** [comment]
Sorry Andrew, but could not understand the point you made

My distributed worker properties file have all the ssl details - ssl.key* , producer.key* and communication with Kafka endpoints is working fine as well. Communication with MQ also works in Mutual SSL mode but only post exporting the env variable "EXTRA_ARGS" with keystore / truststore details. I want to implement mutual SSL with MQ by passing these details to connector process rather than in EXTRA_ARGS (at worker JVM level).
I did add all the parameters in the connector -

mq.ssl.keystore.location	
mq.ssl.keystore.password	
mq.ssl.truststore.location	
mq.ssl.truststore.password	

but getting error.

**Comment by AndrewJSchofield** [comment]
Closing dormant issue.
