### ISSUE TITLE
MQ Source and Sink  connector logs not getting displayed 

### ISSUE THREAD

**Issue by NirupamS82** [ibm-messaging/kafka-connect-mq-source#66]
MQ Source and Sink  connector  debug or any other form of  logs not getting displayed in File or Console  though  both source and Sink getting successfully started and able to connect to IBM MQ and kafka respectively .Tried running the connect-standalone.bat from windows machine .

Is there any setting that has to be explicitly  done, to enable writing the logs to console or File .Pls Advise

**Comment by AndrewJSchofield** [comment]
Well, I use them regularly and the messages are written to stdout. The framework uses log4j so I suggest researching the configuration for that to generate logging information to other places. Should be pretty simple to achieve with configuration.

**Comment by AndrewJSchofield** [comment]
Closing dormant issue.
