### ISSUE TITLE
MQ Source and Sink is not print the logs in the log file

### ISSUE THREAD

**Issue by akshaypatel122826** [ibm-messaging/kafka-connect-mq-source#67]
Able to connect using Source and Sink connector code to IBM MQ and Kafka but logs are not printed in the log file.

Is there any configuration explicitly done to print the logs on log file. Please advise on it.

**Comment by AndrewJSchofield** [comment]
Which log file? The logs are generated to stdout and you can redirect those to wherever you want.

**Comment by AndrewJSchofield** [comment]
Closing dormant issue.
