### ISSUE TITLE
How to to test connector on windows7 in standalone mode?

### ISSUE THREAD

**Issue by mukthyarazam** [ibm-messaging/kafka-connect-mq-source#7]
I am able to setup and run kafka on windows7 as [mentioned](https://dzone.com/articles/running-apache-kafka-on-windows-os), can you please help me with the steps to run the mq-connector or other connector jar on windows. thanks in advance

**Comment by AndrewJSchofield** [comment]
Hi. I don't have a Windows system to try. But, the instructions here (https://github.com/ibm-messaging/kafka-connect-mq-source/blob/master/UsingMQwithKafkaConnect.md) would be very close to what you'd need on Windows. You should not that while Kafka works on Windows, it's not supported by the community and there are known issues. It's fine for experimentation I think but it doesn't work perfectly.

**Comment by mukthyarazam** [comment]
Ok..do we have any other approach to test this connector Uber or fat jar on wibdows7. Can i make this connector as spring boot application if so what changes required ?

**Comment by AndrewJSchofield** [comment]
I don't know Spring Boot so I cannot help with this.
