### ISSUE TITLE
Kafka Message Formatting - JMS Attributes/MQMD Fields as Part of Value Payload

### ISSUE THREAD

**Issue by wwermager** [ibm-messaging/kafka-connect-mq-source#71]
Hello,

We are currently using an MQ Source Connector provided from another vendor and use the Value to Key single message transform to key Kafka messages based on the `.replyTo.name` field as we have an ordering guarantee that needs to be satisfied. We are looking into this connector as an open source alternative. Here's the general format of the data we get using this other mentioned connector:

``` json
{
  "messageID": "ID:###############",
  "messageType": "bytes",
  "timestamp": EPOCH TIME,
  "deliveryMode": 1,
  "correlationID": null,
  "replyTo": {
    "destinationType": "queue",
    "name": "queue://#############/########?targetClient=1"
  },
  "destination": null,
  "redelivered": false,
  "type": null,
  "expiration": 0,
  "priority": 0,
  "properties": {
    Other_JMS_Attributes_Go_Here
    }
  },
  "bytes": "BASE 64 ENCODED JSON STRING",
  "map": null,
  "text": null
}
```

We've tried a multitude of config combinations, to get the JMS and MQMD fields as part of the value payload but have had no success. It seems like we can only get JMS attributes and MQMD fields as part of the headers using the `mq.jms.properties.copy.to.kafka.headers` configuration. 

What are our options if we want to continue keying Kafka messages off of the information our MQ provider gives us in the replyTo field? Would this be possible with the default or json record builders?

**Comment by AndrewJSchofield** [comment]
I think the most straightforward option is to enhance the connector to handle this. It would be possible to use an SMT, but the SMT would need to be JMS-aware I expect, or at least very flexible to extract a nested field like `replyTo.name`. I have a feeling that particular name is related to the specific JMS client you're using, but the principle should work with any connector.

**Comment by wwermager** [comment]
Thanks @AndrewJSchofield  for the quick response your feedback has been very helpful. We will look into possibly enhancing the connector for our use case.
