### ISSUE TITLE
MQ Connection Handling Post Queue Manager Restarts

### ISSUE THREAD

**Issue by wwermager** [ibm-messaging/kafka-connect-mq-source#72]
Hello,

We are currently using another MQ source connector provided by another vendor, however, we are looking at this as a potential alternative. One of the issues we face with our existing implementation is reconnection attempts never end up succeeding for the connector task(s) following queue manager restarts. This requires intervention of restarting all connector tasks.

We will be doing some testing, but is there detection and connection resolution provided by this connector for queue manager restarts?

Thanks in advance!

**Comment by AndrewJSchofield** [comment]
There is nothing special about a queue manager restart as opposed to a listener restart, or a queue manager failover, or a queue manager restart. The connector is designed to reconnect in all of these situations.

**Comment by wwermager** [comment]
That is great news, thank you for the quick response @AndrewJSchofield
