### ISSUE TITLE
issue:no mqjbnd in java.library.path

### ISSUE THREAD

**Issue by praveenkumar928** [ibm-messaging/kafka-connect-mq-source#74]
when I was using binding property ("mq.connection.mode": "bindings") in the connector and getting the Error Caused by: java.lang.UnsatisfiedLinkError: no mqjbnd in java.library.path. I am using MQ client 9x in the class path.

**Comment by AndrewJSchofield** [comment]
The connector just uses a regular JMS client. Just follow the MQ documentation for a bindings-mode JMS application and it will work.

**Comment by praveenkumar928** [comment]
Hi Andrew, My Question is how to pass .bindings file path in the config json (parameter or key). do you have any sample config json file to supply .bindings path. In our case we need to supply .bindings file given by MQ admin team. In MQ java client we do normally like below :
contextConfig.put( InitialContext.INITIAL_CONTEXT_FACTORY, "com.sun.jndi.fscontext.RefFSContextFactory" );
				contextConfig.put( InitialContext.PROVIDER_URL, "file:/C:/test/bindings"); // .bindings file path

**Comment by AndrewJSchofield** [comment]
Hi. The connector doesn't give you a way to work with the JNDI context factory directly. I don't have an "MQ admin team" so I didn't think of this use case. It's not something I've tried personally. I think you'll either need to use a JVM-wide way of setting the configuration, or perhaps the connector needs an enhancement to support it.

**Comment by jhughes24816** [comment]
Hi @praveenkumar928 thank you for your suggestion. I will raise it with the Event Streams development team.
