### ISSUE TITLE
Integration with Schema registry and JSON to AVRO Conversion

### ISSUE THREAD

**Issue by SAshish19** [ibm-messaging/kafka-connect-mq-source#79]
Hi Team,

We are using this connector with a distributed worker. There is a use-case to take incoming JSON message from IBM MQ , integrate the worker with Hortonwoks schema registry and send the data in AVRO format to Kafka. Is this possible with this connector (we are using v1.2.0)

Thanks & Regards

**Comment by AndrewJSchofield** [comment]
Yes, it's possible. Use the JsonRecordBuilder and the AvroConverter.

**Comment by AndrewJSchofield** [comment]
Closing dormant issue.
