### ISSUE TITLE
Facing authorization issue while connecting to mq manager. But there is no ssl enabled on the IBM Mq side.

### ISSUE THREAD

**Issue by pavansai8** [ibm-messaging/kafka-connect-mq-source#8]
Facing authorization issue while connecting to mq manager. But there is no ssl enabled on the IBM Mq side.
java: 1.8
IBM MQ version: 7.5
O.S verison:Red Hat Enterprise Linux Server release 5.11 (

[2018-01-19 07:22:12,477] ERROR MQ error: CompCode 2, Reason 2035 MQRC_NOT_AUTHORIZED (com.ibm.mq.kafkaconnect.JMSReader:309)
[2018-01-19 07:22:12,477] ERROR Exception thrown while calling task.commit() (org.apache.kafka.connect.runtime.WorkerSourceTask:387)
org.apache.kafka.connect.errors.RetriableException: com.ibm.msg.client.jms.DetailedJMSSecurityRuntimeException: JMSWMQ2013: The security authentication was not valid that was supplied for QueueManager '*******' with connection mode 'Client' and host name '$$$$$$$($$$$)'.
Please check if the supplied username and password are correct on the QueueManager to which you are connecting.
        at com.ibm.mq.kafkaconnect.JMSReader.handleException(JMSReader.java:346)
        at com.ibm.mq.kafkaconnect.JMSReader.connectInternal(JMSReader.java:269)

**Comment by AndrewJSchofield** [comment]
I recommend that you get a client connection working with regular MQ interfaces first and then use the same settings (channel name, queue name, MCAUSER, ...) with the connector. It will work with MQ v7.5 but the configuration for such an old MQ release does not support CHLAUTH and so on.

**Comment by pavansai8** [comment]
Hi Andrew,

We got the same settings and parameters working from other clients like Sonic MQ. And I used the same configurations here and I'm getting this error. And we are using any username and password to connect to MQ queue manager host. Is the authorization parameters like username and password are mandatory? 
Below are the parameters we are passing...

name=mq-source
connector.class=com.ibm.mq.kafkaconnect.MQSourceConnector
mq.queue.manager=TESTFORMAT
mq.connection.name.list=$$.$$$.$$$.$$($$$$)
mq.channel.name=MI.SVRCONN
mq.queue=$$$$$
#mq.WMQ_CM_CLIENT=1
mq.transporttype=1
topic=topic1
mq.record.builder=com.ibm.mq.kafkaconnect.builders.DefaultRecordBuilder'

Do you have any suggesstions on this Andrew?

**Comment by pavansai8** [comment]
We use SSL cipher suite to connect to a different queue manager. And kafka mq connector is also failing while trying to establish connection by passing below SSL certificate.
SSLCipherSuite=TLS_RSA_WITH_AES_128_CBC_SHA

**Comment by pavansai8** [comment]
Hi Andrew,

Did you get chance to look at my above comments?

**Comment by AndrewJSchofield** [comment]
I would try specifying EXTRA_ARGS="-Dcom.ibm.mq.cfg.useIBMCipherMappings=false" when you start the Kafka Connect worker. I have always needed to specify that when using TLS with Java. Apart from that, nothing comes to mind. I can successfully connect without specifying a userid/password, so I think we can eliminate that as the cause of the problems.

**Comment by pavansai8** [comment]
Where we need to append this paramter andrew? in the properties file?

**Comment by AndrewJSchofield** [comment]
On the command line that you use to launch Java.
