### ISSUE TITLE
Does it has specific MQ SSL/TLS relevant config items?

### ISSUE THREAD

**Issue by qingyuan18** [ibm-messaging/kafka-connect-mq-source#82]
just want to know whether this plugin has its own specific SSL keystore/trust keystore...etc configuration items , or it all rely on the default Kafka connector SSL/JKS...etc configuration?

Thanks a lot

**Comment by slachiewicz** [comment]
please check here: https://github.com/ibm-messaging/kafka-connect-mq-source#setting-up-mq-connectivity-using-tls-with-a-server-side-certificate - interesting variable for You `mq.ssl.keystore.location`
