### ISSUE TITLE
Kafka Connect source connector's tasks going up and down

### ISSUE THREAD

**Issue by harishanandan124** [ibm-messaging/kafka-connect-mq-source#89]
Occasionally with Kafka Connect, I see my IBMMQ SourceConnector's task go up and down, that is, the REST interface sometimes reports one task that is RUNNING and sometimes reports no tasks (the connector remains RUNNING this whole time). During these times, the task seems to be working when it's running. Then, if I delete and re-create the connector, the problem seems to go away. I suspect something is wrong--that tasks shouldn't churn like this, right? 
I use KAFKA- 2.2.0 and SCALA - 2.12. Does it have to do anything with Kafka version?

**Comment by Joel-hanson** [comment]
Hello @harishanandan124,

I apologize for the extended delay in addressing this issue. Upon reviewing the codebase, I couldn't find any identical problems during my testing. However, it's important to note that the codebase has undergone several changes over the years. Thus, I kindly request you to verify if the issue still persists.
