### ISSUE TITLE
Suggest the approach for new RecordBuilder ?

### ISSUE THREAD

**Issue by b4uazam** [ibm-messaging/kafka-connect-mq-source#9]
Hi Andrew,
We tried this connector repo code and its running successfully. 

thanks for your valuable connector code.
given record builders(default, json) are not suitable for our requirement so can you please suggest best approach/ change to be made in the code base to fulfill below requirement. thanks

IBM MQ example message(input): John31New York20180123
we know the start and end index of each field from the message

Expected json record on kafka topic(output) example: 
{ "**name**": [{name: "John",type: string} ], 
**"age"**:[{name:31, type:int32}],
"**city**":[{name: "New York", type:string}],  
"**BirthDate**": [{name:"20180123", type:date}] 
}

I believe we can fulfill the requirement by creating sub class of [builder](https://github.com/ibm-messaging/kafka-connect-mq-source/blob/master/src/main/java/com/ibm/mq/kafkaconnect/builders/RecordBuilder.java)  

suggest or provide the approach for above json converter.

**Comment by AndrewJSchofield** [comment]
Hi, yes, you're right. You need to create your own builder. Basically, you need to parse the MQ message and generate a SourceRecord which includes all of the information you need in the JSON message. Once you've done that, use org.apache.kafka.connect.json.JsonConverter as the ValueConverter which is used to convert from the SourceRecord into the actual Kafka message.
