### ISSUE TITLE
No connectivity established with MQ in distributed mode

### ISSUE THREAD

**Issue by jagendramishra** [ibm-messaging/kafka-connect-mq-source#91]
Hi,
I am running kafka as AWS Service (MSK) and running kafka-connect as a pod in kubernetes. kafka-connect can establish connection with my MSK but there is no sign of connectivity efforts with MQ.

I can run pod and if I use port forward and access url /connectors then results come as [] but if I try /connector-plugins then I see 3 classes. But I am not finding how my pod is going to connect to MQ. There are no errors also where it is trying to connect to MQ. I am kind of lost.

Could anyone please suggest how to establish connectivity with MQ which is running on-prem.
Thanks & regards,
Jagendra

**Comment by its-dave** [comment]
You can follow the [README](https://github.com/ibm-messaging/kafka-connect-mq-source#readme) or the [Event Streams documentation](https://ibm.github.io/event-streams/connecting/mq/) to set up connectors to MQ.
